### ISSUE TITLE
Order of the GPIO used

### ISSUE THREAD

**Issue by DarkElvenAngel** [jjsch-dev/pico_i2c_sniffer#4]
This is more of a question as I was looking to write my own I2C sniffer but since the wheel exists why make a new one?

I'm just curious to know the order of the GPIO you have used was there a reason for that? I'm looking to build this project for the Debug Probe if it will work and I would need to reorder the GPIO for that to work,  from I see in the code that shouldn't be an issue but I thought I would ask since the SDA and SDC lines aren't next to each other like one might expect.

**Comment by jjsch-dev** [comment]
Hello @DarkElvenAngel , it's been a long time since I wrote this routine, and I don't remember the details well. I think I remember that the choice of pins is related to the coding of the I2C bus conditions, DATA, START, STOP, and the PIO capabilities with the MOVE, IN and JMP instructions.

; two pins are used to communicate the event code. 
; To use the JMP pin, the lsb event bit is turned off to indicate data.
.define PUBLIC EV_DATA     0x00
.define PUBLIC EV_START    0x01
.define PUBLIC EV_STOP     0x03

**Comment by DarkElvenAngel** [comment]
Thank you for your reply,

I understand it a bit more about the code now and I managed some shuffling to get things to work on the Debug Probe.  I have it so the EV_xxxx conditions show on the LEDs unavoidable side effect of how this works.  It works great thank you for making this open source.

I'll close this issue thank you again.
